project:
  type: website
  output-dir: docs

website:
  title: "Dennis Chumakov"
  favicon: favicon/favicon.ico
  navbar:
    title: false
    logo: images/dc_logo.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: experience.qmd
        text: Experience
      - href: projects/index.qmd
        text: Projects
      - href: photography.qmd
        text: Photography
      - href: reflection.qmd
        text: Reflection
      - href: contact.qmd
        text: Contact
    right:                                        #Nav left/right split to prevent overcrowding. 
      - href: cv/Dennis-Chumakov-CV.pdf
        text: "CV"
        target: _blank                            #So CV opens in a new page. 
      - icon: github
        href: https://github.com/dennis-chumakov
        target: _blank  
  page-footer:
    left: "© 2025 Dennis Chumakov"
    right: "Built with [Quarto](https://quarto.org)"

format:
  html:
    theme:
      - lux
      - styles.scss
    toc: false
    page-layout: full



