project:
  type: website
  output-dir: docs

website:
  title: "Dennis Chumakov"
  favicon: favicon\favicon.ico
  navbar:
    title: false
    logo: images\dc_logo.png
    right:
      - href: index.qmd
        text: Home 
      - href: about.qmd
        text: About Me
      - href: projects.qmd
        text: Projects
      - href: experience.qmd
        text: Experience
      - href: gallery.qmd
        text: Gallery

format:
  html:
    theme:
      - lux
      - styles.scss
    toc: false
    page-layout: full



