project:
  type: website
  output-dir: docs

website:
  title: "Dennis Chumakov"
  favicon: images\favicon.ico
  navbar:
    title: false
    logo: images\dc_logo.png
    right:
      - href: about.qmd
        text: About Me
      - href: index.qmd
        text: Home 

format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    toc: true



